function ApplyOverrides()
    -- Autogenerated IO path overrides

    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart client: IO path overrides are added")
    Ext.Utils.Print("")
end

function EnableGodsForAllClasses()
    for _, resourceGuid in pairs(Ext.StaticData.GetAll("ClassDescription")) do
        if (Ext.StaticData.Get(resourceGuid, "ClassDescription").HpPerLevel > 0) then
            Ext.StaticData.Get(resourceGuid, "ClassDescription").HasGod = true
        end
    end
end

function EnableSharForAllRaces()
    for _, resourceGuid in pairs(Ext.StaticData.GetAll("ClassDescription")) do
        if (Ext.StaticData.Get(resourceGuid, "ClassDescription").HpPerLevel > 0) then
            Ext.StaticData.Get(resourceGuid, "ClassDescription").HasGod = true
        end
    end
end

Ext.Events.ModuleLoadStarted:Subscribe(function (e)
    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart client: ModuleLoadStarted")
    Ext.Utils.Print("")

    ApplyOverrides()
end)

Ext.Events.StatsLoaded:Subscribe(function (e)
    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart client: StatsLoaded")
    Ext.Utils.Print("")

    ApplyOverrides()
    --EnableGodsForAllClasses()
end)
