function ApplyOverrides()
    -- Autogenerated IO path overrides

    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart server: IO path overrides are added")
    Ext.Utils.Print("")
end

Ext.Events.ModuleLoadStarted:Subscribe(function (e)
    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart server: ModuleLoadStarted")
    Ext.Utils.Print("")

    ApplyOverrides()
end)

Ext.Events.StatsLoaded:Subscribe(function (e)
    Ext.Utils.Print("")
    Ext.Utils.Print("ReallyShadowheart server: StatsLoaded")
    Ext.Utils.Print("")

    ApplyOverrides()
end)

Ext.Utils.Print("")
Ext.Utils.Print("ReallyShadowheart server: subcribed to engine events")
Ext.Utils.Print("")
